# Generated by Django 5.2.1 on 2025-06-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'verbose_name': 'Revenue Item', 'verbose_name_plural': 'Revenue Items'},
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sweat_tracker.currency'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='gross_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='revenue',
            name='net_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='revenue',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_items', to='sweat_tracker.project'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='source_description',
            field=models.TextField(blank=True),
        ),
    ]
