# Generated by Django 5.2.1 on 2025-06-02 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0002_alter_currency_options_alter_revenue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='date_received',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
