# Generated by Django 5.2.1 on 2025-06-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0003_revenue_date_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='gross_revenue',
            new_name='gross_amount',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='net_revenue',
            new_name='net_amount',
        ),
    ]
