# Generated by Django 5.2.1 on 2025-06-02 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0004_rename_gross_revenue_revenue_gross_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='date_completed',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
