# Generated by Django 5.2.1 on 2025-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0005_contribution_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contribution_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='work_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='work_units',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
