# Generated by Django 5.2.1 on 2025-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0006_alter_contribution_contribution_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
