# Generated by Django 5.2.1 on 2025-06-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0007_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
