# Generated by Django 5.2.1 on 2025-06-02 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0009_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_items', to='sweat_tracker.organization'),
        ),
    ]
