# Generated by Django 5.2.1 on 2025-06-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0010_revenue_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contributor_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='sweat_tracker.role'),
        ),
    ]
