# Generated by Django 5.2.1 on 2025-06-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0011_contribution_contributor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='sweat_tracker.organization'),
        ),
    ]
