# Generated by Django 5.2.1 on 2025-06-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0012_contribution_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='work_units',
            new_name='units',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='contribution',
            name='value_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('hourly_work', 'Hourly Work'), ('expense', 'Expense'), ('investment', 'Investment'), ('work_package', 'Work Package')], default='hourly_work', max_length=20),
        ),
    ]
