# Generated by Django 5.2.1 on 2025-06-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0014_remove_contribution_contribution_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='units',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='value_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
