# Generated by Django 5.2.1 on 2025-06-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweat_tracker', '0015_alter_contribution_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
